[package]
name = "consumer"
version = "0.1.0"
authors = ["alex179ohm <alex179ohm@gmail.com>"]
edition = "2018"

[dependencies]
nsq-client = { path = "../../", features = ["nativetls"] }
env_logger = "0.6"
log = "0.4"
